version: "3.8"   # or whatever version you're using
services:
  mysql:
    image: mysql:8
    container_name: my-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=secret"]
      interval: 5s
      timeout: 2s
      retries: 10
      start_period: 10s

volumes:
  mysql_data:
